apiVersion: v1
kind: ConfigMap
metadata:
  name: websocket-app-config
  namespace: websocket-app
data:
  PHX_HOST: "websocket-app.example.com"
  PORT: "4000"
  DATABASE_URL: "ecto://postgres:postgres@postgres-service:5432/websocket_app"
  SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
  PHX_SERVER: "true"
  POOL_SIZE: "20"
  RELEASE_COOKIE: "${RELEASE_COOKIE}"
  ERL_FLAGS: "-proto_dist inet6_tcp"