apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: websocket-app
type: Opaque
stringData:
  password: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: websocket-app
type: Opaque
stringData:
  SECRET_KEY_BASE: "your_generated_secret_key_base_here"
  RELEASE_COOKIE: "your_release_cookie_here"