[package]
name = "websocket-load-tester"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-tungstenite = "0.17"
futures = "0.3"
url = "2.2"
serde_json = "1.0"
clap = { version = "3.0", features = ["derive"] }
indicatif = "0.16"
